# Generated by Django 2.2.11 on 2020-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('donnees', models.TextField()),
                ('previous_hash', models.CharField(max_length=1000)),
                ('hash_block', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contravention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100)),
                ('destinataire', models.CharField(max_length=100)),
                ('typeC', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Permis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=60)),
                ('nom', models.CharField(max_length=40)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=40)),
                ('date_delivrance', models.DateField()),
                ('date_expiration', models.DateField()),
                ('numero', models.IntegerField()),
                ('groupe_sanguin', models.CharField(max_length=3)),
                ('categorie_vehicule', models.CharField(max_length=2)),
            ],
        ),
    ]
