# Generated by Django 2.2.11 on 2020-03-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permis_a_point', '0002_auto_20200310_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='stagiaire',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='conducteur',
        ),
        migrations.RemoveField(
            model_name='contravention',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='contravention',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='conducteur',
        ),
        migrations.DeleteModel(
            name='AgentSecurite',
        ),
        migrations.DeleteModel(
            name='Attestation',
        ),
        migrations.DeleteModel(
            name='CentreStage',
        ),
        migrations.DeleteModel(
            name='Conducteur',
        ),
        migrations.DeleteModel(
            name='Contravention',
        ),
        migrations.DeleteModel(
            name='Permis',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
