# Generated by Django 2.2.7 on 2020-03-11 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permis_a_point', '0004_auto_20200310_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
