# Generated by Django 2.2.7 on 2020-03-11 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permis_a_point', '0005_auto_20200311_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
