# Generated by Django 2.2.7 on 2020-03-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permis_a_point', '0006_conducteur_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducteur',
            name='conducteur',
        ),
    ]
