# Generated by Django 2.2.7 on 2020-03-12 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permis_a_point', '0008_auto_20200312_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='permis',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete='CASCADE', to='permis_a_point.Permis'),
            preserve_default=False,
        ),
    ]
