# Generated by Django 2.2.11 on 2020-09-13 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permis_a_point', '0010_auto_20200912_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='categorie',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
